export const accentMap = {
    blue: {
        text: 'text-blue-700',
        bg: 'bg-blue-600',
        light: 'bg-blue-50',
        border: 'border-blue-600',
        shadow: 'shadow-blue-200',
        gradient: 'from-blue-700 to-slate-900',
    },
    indigo: {
        text: 'text-indigo-700',
        bg: 'bg-indigo-600',
        light: 'bg-indigo-50',
        border: 'border-indigo-600',
        shadow: 'shadow-indigo-200',
        gradient: 'from-indigo-700 to-slate-900',
    },
    emerald: {
        text: 'text-emerald-700',
        bg: 'bg-emerald-600',
        light: 'bg-emerald-50',
        border: 'border-emerald-600',
        shadow: 'shadow-emerald-200',
        gradient: 'from-emerald-700 to-slate-900',
    },
    amber: {
        text: 'text-amber-700',
        bg: 'bg-amber-500',
        light: 'bg-amber-50',
        border: 'border-amber-500',
        shadow: 'shadow-amber-200',
        gradient: 'from-amber-600 to-slate-900',
    },
    rose: {
        text: 'text-rose-700',
        bg: 'bg-rose-600',
        light: 'bg-rose-50',
        border: 'border-rose-600',
        shadow: 'shadow-rose-200',
        gradient: 'from-rose-700 to-slate-900',
    },
    purple: {
        text: 'text-purple-700',
        bg: 'bg-purple-600',
        light: 'bg-purple-50',
        border: 'border-purple-600',
        shadow: 'shadow-purple-200',
        gradient: 'from-purple-700 to-slate-900',
    },
    teal: {
        text: 'text-teal-700',
        bg: 'bg-teal-600',
        light: 'bg-teal-50',
        border: 'border-teal-600',
        shadow: 'shadow-teal-200',
        gradient: 'from-teal-700 to-slate-900',
    },
};
